language: php

php:
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate

script: phpunit

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: heroku
  app: merchstore1
  api_key:
    secure: qwerty
