sudo: required
dist: trusty

language: php
php:
  - 7.1

env:
  - NODE_RELEASE=5.x

before_install:
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs

before_script:
  - php artisan cache:clear
  - php artisan view:clear
  - php artisan config:cache

install:
  - composer install
  - npm install

script:
  - vendor/bin/phpunit
  - npm run dev
deploy:
  provider: heroku
  app: merchstore1
  on:
    repo: fablerq/MerchStore
