language: php

php:
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate

script: phpunit

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: heroku
  api_key:
    secure: dn3f7/wOQ5lnXwziePtgSnJKM9yWILnodDKC52eiQmD5jSIDqpH1i0yy2ztPKDlTScR7E2So6FzgYxqxGjlrUbQ5H+SqmijAD0RYWe7CmgmJ4g/9srQoPtgpzXcnpO8ImrmQqHVs3HKcXv4iexREFuQw9/pksTnvc0d2/h91mY/XQBn0mxWQtq0iI53XTdgwPHj2kODg9Ir1Roa290BRXkSROGU3Az1OcR1MzS85q5K5/nM/sHyKl8ejUU2xUOHGcH0+5aiTBgcMNolc3LmI0nbpOZ1pmSRTQlnP5VpZEqF0q8SWS97qbe6EXa0Y6X/u2CKYjZ2KEsLTJCfYr/lTyBSsIjXEHQhoX2TTlWJH8TN25OlHuVlnMU+BUMky895jSLqx81S289lgl/eDh8l5KTDj9h/CLBe+6vhl3MjX+f6sMKsZS7eNRxHKvx/mxTwXjXVrnbNNx/tp/+ZoaJvvaa6z08IYqxFR+jKD9G3c4M8s7FV9Y9yWWH6OHq+4HQLaUX5FPFxiMZMOuXRxa3JmTQH4HRTYMaXbB9NlR6rU8bGVIOo2OjqGGg8Wd2sJB54REtAiuaKu61uQpEF0LFq3V144O88ciM98ra9ywgE81EUCOSWRiLonOmCaY8QHVgEFD1JYZcBt6g7XZmtlm1tY2HuVDr5xqqeS9iFnYvGnDLA=
  app: merchstore1
  on:
    repo: fablerq/MerchStore
